/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class LocalAsrEngine */

#ifndef _Included_LocalAsrEngine
#define _Included_LocalAsrEngine
#ifdef __cplusplus
extern "C" {
#endif

/*
 * Class:     LocalAsrEngine
 * Method:    markProcess
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_unisound_aios_adaptationtrain_JNI_LocalAsrEngine_markProcess
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
